name: trex-ci
version: 0.1.0.0
github: "jhamPac/trex-ci"
license: BSD3
author: "jhampac"
maintainer: "cloud@kevia.me"
copyright: "2021 jhampac"

extra-source-files:
    - README.md
    - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: https://github.com/jhamPac/trex-ci#readme

default-extensions:
    - BlockArguments
    - DeriveAnyClass
    - DeriveGeneric
    - LambdaCase
    - NoImplicitPrelude
    - OverloadedStrings
    - StrictData

dependencies:
    - base >= 4.7 && < 5
    - aeson
    - async
    - butcher
    - hslogger
    - http-client - http-conduit - http-types
    - network
    - record-hasfield - rio
    - scotty
    - serialise
    - stm
    - time
    - typed-process
    - wai-cors
    - yaml

ghc-options:
    - -F -pgmF=record-dot-preprocessor

library:
    source-dirs: src

executables:
    trex-ci-exe:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - trex-ci

tests:
    trex-ci-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - trex-ci
            - hspec
            - QuickCheck
